// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecreaseSpeed():Promise<void>;

export function IncreaseSpeed():Promise<void>;

export function QuitApp():Promise<void>;
