// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecreaseSpeed() {
  return window['go']['main']['App']['DecreaseSpeed']();
}

export function IncreaseSpeed() {
  return window['go']['main']['App']['IncreaseSpeed']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}
